name: Teleport Setup
author: Gravitational, Inc.
description: Installs `tsh`, `tbot` and `tctl`.
inputs:
    version:
        description: Specify the Teleport version without the preceding "v"
        required: true
runs:
    using: node16
    main: dist/index.js
branding:
    color: purple
    icon: terminal
