name: Teleport Setup
author: Gravitational, Inc.
description: Installs `teleport`, `tsh`, `tbot` and `tctl`.
inputs:
    enterprise:
        description: Specify whether to use the enterprise binaries.
        required: false
        default: "false"
    proxy:
        description: Specify the address of your Teleport Proxy, required if version is set to "auto".
        required: false
    version:
        description: Specify the Teleport version without the preceding "v" or specify "auto" to use the version indicated by your Teleport cluster.
        required: true
runs:
    using: node24
    main: dist/index.js
branding:
    color: purple
    icon: terminal
